### ISSUE TITLE
Vello 0.1 release

### ISSUE THREAD

**Issue by nicoburns** [linebender/vello#302]
### Blocking Tasks
- [ ] Robust dynamic memory
- [ ] Artifacts above 64k draw objects
- [x] [Peniko release](https://github.com/linebender/peniko/issues/17)
- [x] ~[Fello](https://github.com/dfrg/fount) release~ (now replaced by [read-fonts](https://github.com/googlefonts/fontations/tree/main/read-fonts))
- [x] Expanded CI coverage - see #250

**Comment by simbleau** [comment]
@nicoburns @raphlinus is this issue tracking the first crates.io publish of vello?

Can we clarify the goal through title or otherwise.

**Comment by raphlinus** [comment]
Yes, this is tracking the crates.io publication. Progress on the issues listed has been slow, I've decided to prioritize stroke rework ahead of it, and that's taking a long time.

**Comment by PoignardAzur** [comment]
As mentioned on Zulip, we're getting to a point where we're encouraging people to use vello, and where some people actually are experimenting with it (eg bevy_vello).

This makes it more important to have a release soon, for several reasons:

- To avoid namesquatting
- So people can add our crate with a simple `cargo add`
- So our dependents can publish on crates.io themselves
- To have documentations up on crates.io
- Simply because not having a crate up makes us look somewhat unserious.

So, questions:

- How much progress have we made on "Robust dynamic memory"?
- How much progress have we made on "Artifacts above 64k draw objects"?
- Do we have a concrete plan to make progress on these issues in the coming weeks?
- Are these issues legitimate blockers that would seriously hamper usability for someone pulling the crate just to hack with it. Could we just put a warning label on the README that says "Caution: this crate has so and so problem, be aware of it" and publish?
- What's the status of our documentation?
- Would someone be available to do a documentation pass? How long would it take?
- What's blocking us from publishing peniko and fello?

**Comment by pieterdd** [comment]
Regarding the namesquatting concern, since this has some urgency: you could publish an empty placeholder crate like [floem](https://crates.io/crates/floem) did to reserve its spot. I think they ran `cargo new`, edited the Cargo.toml fields accordingly, and then published. You may want to create a placeholder README.md file as well before publishing to redirect crates.io visitors accordingly, as shown [here](https://crates.io/crates/floem-ui-kit).

It's a few minutes of work but then you have piece of mind.

**Comment by nicoburns** [comment]
Vello 0.1 is now released!
