### ISSUE TITLE
The process of calculating the bbox of the path seems odd

### ISSUE THREAD

**Issue by caxieyou** [linebender/vello#319]
Hi there~

So in the pathseg.wgsl file, the following code try to get the bbox of a path from the:  Cubic's start end control-1 and contril-2 ponits.
    let transform = read_transform(config.transform_base, tm.trans_ix);
        **p0 = transform_apply(transform, p0);
        p1 = transform_apply(transform, p1);**
        **var bbox = vec4(min(p0, p1), max(p0, p1));**
        // Degree-raise
        if seg_type == PATH_TAG_LINETO {
            p3 = p1;
            p2 = mix(p3, p0, 1.0 / 3.0);
            p1 = mix(p0, p3, 1.0 / 3.0);
        } else if seg_type >= PATH_TAG_QUADTO {
            **p2 = transform_apply(transform, p2);**
            **bbox = vec4(min(bbox.xy, p2), max(bbox.zw, p2));**
            if seg_type == PATH_TAG_CUBICTO {
                **p3 = transform_apply(transform, p3);
                bbox = vec4(min(bbox.xy, p3), max(bbox.zw, p3));**
            } else {
                p3 = p2;
                p2 = mix(p1, p2, 1.0 / 3.0);
                p1 = mix(p1, p0, 1.0 / 3.0);
            }
        }

But this seems really confusing to me.

I think the correct way should be finding the extremities...

Thanks

**Comment by DJMcNab** [comment]
https://github.com/linebender/vello/blob/006faab69fc519c9c7ed6002be740914efad9ffe/shader/pathseg.wgsl#L163-L183

I don't have enough expertise to know what this code does otherwise.
Can you provide input for which this fails?

This sounds like https://stackoverflow.com/questions/24809978/calculating-the-bounding-box-of-cubic-bezier-curve? (Pattern matching, I'd speculate that p0-p3 are providing the coordinates of the control polygon of the segment, but I can't defend that position)

**Comment by caxieyou** [comment]
Thanks for the reply

By saying odd, I mean the bbox from the 4 points sometimes maybe bigger than what we really need, which can cause clipping or early return stuff in the following steps slow cuz you need to consider more bins and tiles.

<img width="325" alt="1683763312244" src="https://github.com/linebender/vello/assets/6970846/c34ad0be-a3b4-4615-b0b1-60573358aa3f">

**Comment by caxieyou** [comment]
Yes thanks a lot, that makes much sence now.
Yeah I can understand there should be a lot of "if else" cases if we want to get a tight bbox. which might slow down the speed first.
