### ISSUE TITLE
Should `timestamp_period` on `RendererOptions` be behind the `wgpu-profiler` feature flag? 

### ISSUE THREAD

**Issue by bzm3r** [linebender/vello#328]
The `RendererOptions` struct has an additional `timestamp_period` member due to https://github.com/linebender/vello/pull/304: 

https://github.com/linebender/vello/blob/6d57093cc275589843766b8c898793f8147ed323/src/lib.rs#LL81C4-L81C4

As the doc comment explains, `timestamp_period` is used when the `wgpu-profiler`. Should the `timestamp_period` member therefore be put behind the `wgpu-profiler` flag, like so:

```rust
pub struct RendererOptions {
    /// The format of the texture used for surfaces with this renderer/device
    /// If None, the renderer cannot be used with surfaces
    pub surface_format: Option<TextureFormat>,
    /// The timestamp period from [`wgpu::Queue::get_timestamp_period`]
    /// Used when the wgpu-profiler feature is enabled
    #[cfg(feature = "wgpu-profiler")]
    pub timestamp_period: f32,
}
```
Or is it not being behind the feature flag intentional?

**Comment by DJMcNab** [comment]
The intention there was to not require code changes on the user side *because* wgpu-profiler was enabled.

For example, if a library depends on `Vello` , and then a crate depends on that library and Vello, then enables profiling in the top-level crate would break the library, if it managed its own renderers.

Perhaps we should instead accept a reference to the queue in the options? It's a bit messy any way around

**Comment by bzm3r** [comment]
Hmm, I think I understand. 

Is there any prior art here that might be relevant?

**Comment by DJMcNab** [comment]
That field was removed in #398 

Thanks for your well documented feature request
