### ISSUE TITLE
Potentially inaccurate clip_reduce bindings in shader build

### ISSUE THREAD

**Issue by jonathanolson** [linebender/vello#330]
I'm tinkering with a few things, and noticed a discrepancy in the bindings for the clip_reduce shader. I'm curious if this is intended, or I'm missing something (hopefully it's a helpful report).

The ShaderInfo and build output from `crate build` under `crates/shaders/` seems to be missing the Uniform binding.

Steps to reproduce:

1. Cloned fresh checkout of vello (probably unnecessary)
2. `cd vello/crates/shaders/`
3. `cargo build` (also similar with --release)
4. The generated shaders.rs file (under target/debug/build/vello_shaders-0f98b3bcd5fa0642/out/shaders.rs, although the hash seems to be randomly generated, it will be one of the two most recently generated directories starting with `vello_shaders-`) shows only 4 bindings, with Uniform missing:

```rust
        clip_reduce: ComputeShader {
            name: Cow::Borrowed("clip_reduce"),
            workgroup_size: [256, 1, 1],
            bindings: Cow::Borrowed(&[BufReadOnly, BufReadOnly, Buffer, Buffer]),
```

However in `src/shaders.rs`, clip_reduce is noted has having a uniform binding:

```rust
    let clip_reduce = engine.add_shader(
        device,
        "clip_reduce",
        preprocess::preprocess(shader!("clip_reduce"), &empty, &imports).into(),
        &[
            BindType::Uniform,
            BindType::BufReadOnly,
            BindType::BufReadOnly,
            BindType::Buffer,
            BindType::Buffer,
        ],
    )?;
```

This is also backed up by `clip_reduce.wgsl` having the config uniform in binding 0, and additionally I'm getting WebGPU createComputePipeline issues without the additional uniform:

```
The buffer type in the shader (BufferBindingType::ReadOnlyStorage) is not compatible with the type in the layout (BufferBindingType::Storage).
 - While validating that the entry-point's declaration for @group(0) @binding(2) matches [BindGroupLayout "clip_reduce bindGroupLayout"]
 - While validating the entry-point's compatibility for group 0 with [BindGroupLayout "clip_reduce bindGroupLayout"]
 - While validating compute stage ([ShaderModule "clip_reduce"], entryPoint: main).
 - While calling [Device].CreateComputePipeline([ComputePipelineDescriptor "clip_reduce pipeline"]).
 ```

I can't find the reason for the discrepancy yet, I didn't look into whether `wgsl::parse_str(&source)?.global_variables` was missing the entry.

**Comment by jonathanolson** [comment]
`path_coarse_full` and `fine` also had similar discrepancies, there's a decent chance I was using something that was stale.

**Comment by armansito** [comment]
I think this happens because the bindings generated by the build script exclude those that aren't reachable by the entry point. The `config` buffer is not used by `clip_reduce`, hence it's not listed in the entry point resource list that we get from Naga.

This comes up when you use the shaders crate in your own custom renderer. When targeting WebGPU the bindings need to actually match the declared shader text, however when targeting a native backend (e.g. Metal) the binding list that is returned by the crate is the one you want, since the unreachable resources won't be present in the shader source.

I suggest we fix this by making the bindings list a part of the backend-specific data list, such that separate bindings are accessed via the `wgsl` and `msl` fields in the `ComputeShader` type. I'm happy to take this on since I'm going to run into this problem very soon in our integration with Skia's Dawn backend (I already had to work around this on the Skia side for the Metal backend). I think this would also help us resolve discrepancies in resource binding index assignments across the target backends in general.

I've been also meaning to do a clean up pass and remove unused bindings from the shaders at some point.
