### ISSUE TITLE
Incorrect clipping

### ISSUE THREAD

**Issue by jonathanolson** [linebender/vello#333]
In https://github.com/jonathanolson/vello/commit/6eea43d8d77576e36b15bd578f549a04676e6e1e, I have a test scene that is rendering content outside of a defined clip area:

<img width="52" alt="image" src="https://github.com/linebender/vello/assets/480878/341be5cb-a4bf-4142-96d2-6d0170d2909c">

Where a rectangular clipping area is applied (where the blue rectangle is visible, it covers the entire region). The red rectangle should not appear. The green rectangle and blue rectangle are correctly clipped.

```rust
let large_background_rect = kurbo::Rect::new(
    -1000.0, -1000.0,
    2000.0, 2000.0
);
let inside_clip_rect = kurbo::Rect::new(
    11.0, 13.399999999999999,
    59.0, 56.6
);
let outside_clip_rect = kurbo::Rect::new(
    12.599999999999998, 12.599999999999998,
    57.400000000000006, 57.400000000000006
);
let clip_rect = kurbo::Rect::new(
    0.0, 0.0,
    74.4, 339.20000000000005
);
let scale = 0.8876953125;

sb.push_layer( BlendMode { mix: peniko::Mix::Normal, compose: peniko::Compose::SrcOver}, 1.0, Affine::new([scale, 0.0, 0.0, scale, 27.07470703125, 176.40660533027858]), &clip_rect);

sb.fill( peniko::Fill::NonZero, kurbo::Affine::new([scale, 0.0, 0.0, scale, 27.07470703125, 176.40660533027858]), peniko::Color::rgb8(0, 0, 255), None, &large_background_rect);
sb.fill( peniko::Fill::NonZero, kurbo::Affine::new([scale, 0.0, 0.0, scale, 29.027636718750003, 182.9755506427786]), peniko::Color::rgb8(0, 255, 0), None, &inside_clip_rect);
sb.fill( peniko::Fill::NonZero, kurbo::Affine::new([scale, 0.0, 0.0, scale, 29.027636718750003, 559.3583631427786]), peniko::Color::rgb8(255, 0, 0), None, &outside_clip_rect);

sb.pop_layer();
```

This came up in the clip area used for our carousel component, where clipped content shows below the carousel:
<img width="130" alt="image" src="https://github.com/linebender/vello/assets/480878/4a625c75-84e4-4312-968b-e62e0ae8aee6">

**Comment by jonathanolson** [comment]
https://github.com/jonathanolson/vello/commit/a6045b0043f87d11d7b84149cdf5d938f0f0030c has the full scene that contains the carousel example above (it's encoded in JS code, I'm able to record/combine/export that into rust code to display an identical scene, but SceneBuilder doesn't expose a compatible API so I have to patch visibilities of things to get running examples)

**Comment by DJMcNab** [comment]
Reminds me of #286, I think

**Comment by raphlinus** [comment]
Thanks for the clear repro case! We've been picking up hints of clipping errors for a while, but haven't been able to track it down precisely.

**Comment by armansito** [comment]
Does the pixel row right below the bottom edge of `outside_clip_rect` happen to be tile aligned (i.e. the pixel coordinate is a multiple of 16)?

I ask because I've been trying to root cause a similar issue with clipping and I'm wondering if it's also related to @DJMcNab 's observation on [#286](https://github.com/linebender/vello/issues/286#issuecomment-1448967820). I use vello to rasterize coverage masks that are laid out in an atlas texture where each mask is clipped to the axis-aligned bounding box of its atlas allocation. If a mask shape happens to fall entirely outside the bounding box it doesn't get clipped out as it should:

![image](https://github.com/linebender/vello/assets/6933700/c1f3d0ac-afff-46af-8056-b97770cfeabc)

That section of the stroke should get entirely clipped out but instead it gets incorrectly drawn but clipped right at the edge of the tile that covers the shape.

**Comment by armansito** [comment]
#335 fixes this bug. I added @jonathanolson's repro code to a new test scene that demonstrates the problem and the fix.

**Comment by armansito** [comment]
Please re-open if you're still seeing this issue on main.
