### ISSUE TITLE
support for importing external textures (dmabufs on linux)

### ISSUE THREAD

**Issue by dvc94ch** [linebender/vello#337]
Seems like this is not supported by webgpu yet. Use cases for importing dmabufs would be screencasting, embedding a camera feed or hardware accelerated video decoding.

**Comment by DJMcNab** [comment]
I'm not sure this is an actionable issue, although there are a couple of aspects here:

- For video/camera feed/screencasting, AIUI, the ideal solution would be for the compositor itself to handle these, rather than compositing those within vello (because otherwise you get added latency)
- We are not planning to support an image import mechanism other than wgpu `Texture`s, at least in the normal Rust frontend
   As such, if you need this, the change will need to be driven on the wgpu end, so that it can help all projects which use wgpu

I'll wait to hear from @raphlinus or otherwise, but I'm inclined to close this issue (especially if there's an upstream wgpu issue)

**Comment by dvc94ch** [comment]
Is there more information on how that would work? I think flutter/sdl and all other gui libraries do the compositing themselves. Is there some kind of wayland extension that would allow for this? And how would for example xilem handle this? Or are you suggesting it should be handled at an even higher level?

**Comment by dvc94ch** [comment]
I see your point. So you'd render a placeholder and have some Wayland extension to render a pipewire video source. I don't think it exists yet, but someone could design/implement something like that.
