### ISSUE TITLE
bitmap and gradients support

### ISSUE THREAD

**Issue by eliasnaur** [linebender/vello#38]
The pipeline supports uniform colors. I'd like to work on expanding that to accept bitmaps, and later on gradients. If you have any thoughts on the design, let me know. If not, I'll come up with something to start the discussion.

**Comment by raphlinus** [comment]
As it turns out, I have been thinking about this quite a bit, and did some explorations over the weekend. I'll write up my detailed thoughts later today.

**Comment by raphlinus** [comment]
As promised, here are my thoughts on adding images to the piet-gpu pipeline.

A few general thoughts, then I'll get into specifics. One characteristic of a retained-mode pipeline like piet-gpu is that *all* resources have to be resident at the time rendering starts. This is in some contrast to using rasterization to draw images; you can load an image, do the draw call, then the image no longer has to be resident after that. The images can only be freed after the pipeline completes (ie after the fence for the command buffer is signaled). This will require some lifetime tracking on CPU-side objects that hold handles to GPU-side texture resources.

Also, because piet-gpu is using the equivalent of an ubershader, the descriptor set provided to the fine rasterizer has to be able to access all images. There are two fundamental approaches to this. One is to use an array of textures, and build the descriptor set provided to the fine rasterizer with this array. There's a [good blog](http://kylehalladay.com/blog/tutorial/vulkan/2018/01/28/Textue-Arrays-Vulkan.html) on that technique. The other is to use atlasing techniques, so there is a smaller (likely bounded) number of textures, the images are copied into subregions of those textures, then the description of an image consists of a uv rectangle within one of those textures.

There are problems with each. Texture arrays are a relatively newer feature, and, while supported pretty well on Vulkan (and [DX12](https://docs.microsoft.com/en-us/windows/win32/direct3d12/resource-binding-in-hlsl) and recent iterations of Metal), support on older APIs is lacking. Even on Vulkan, the runtime [bound on the maximum number of textures supported in an array](https://vulkan.gpuinfo.org/displaydevicelimit.php?name=maxDescriptorSetSampledImages) may not be adequate for the scene being rendered, especially on older Intel GPUs and Android, and in fact the feature ([VK_EXT_descriptor_indexing](https://vulkan.gpuinfo.org/displayextension.php?name=VK_EXT_descriptor_indexing)) is not absolutely required; support seems especially poor on Android. There may be a performance cost to large arrays, but this is less clear. Again, there's a pretty good blog that goes into more detail on [descriptor indexing](http://chunkstories.xyz/blog/a-note-on-descriptor-indexing/).

Atlasing has its own problems. There's obviously more copying, but additional concerns on top of that. The shader has to do its own logic to deal with the image bounds, making sure that reads beyond the bounds don't sample other images in the atlas (this is particularly challenging with filtered sampling, and mipmapping may not be practical). As mentioned above, *all* images need to be stored in these atlases, so the size of the atlas image may grow. And of course there's the complexity of allocating space in the atlas, as well as possibly additional synchronization concerns, as I think in general it's not ok to write into the atlas while it's being read, even if the regions are disjoint. Note: in Rust, a good approach to (dynamic) atlas allocation is [guillotiere](https://docs.rs/guillotiere/0.6.0/guillotiere/).

Even so, for the pipeline I'm concerned about not just images, but two other image-like resources. Gradients are mentioned above, and there are also cached glyphs, especially those rendered by the platform to match the appearance of native UI text. It's possible but not efficient to do one (small, 1D) image per gradient, but for text atlasing is almost required.

My inclination is to use arrays of textures for images, and potentially add an atlased path later for compatibility. I think ultimately it's simpler, and probably will be higher performance.

Here's my take on the impact on the pipeline stages:

## Encoding

The encoding task really breaks down into two pieces: resource staging, and the encoding of an image element.

### Resource staging

Getting a CPU-side image into a VkImage is a multistage process. I think the best way to do it is this:

* Allocate a buffer (same as now) with host-compatible memory type
* Copy image data into buffer (same as now)
* Allocate an image (same as now) in device memory
* Encode a command buffer that [copies the buffer to the image](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/vkCmdCopyBufferToImage.html), then does an image pipeline barrier
* Submit the command

When the command completes (the fence is signaled), the buffer can then be deallocated. I was originally pretty concerned about synchronization between the image being uploaded and it being available for rendering, but I believe as long as the fine rasterizer is in the same queue as the copy (and there's an appropriate pipeline barrier), things should be ok.

Ultimately, we should probably allow image uploading from multiple threads. This will require some work but nothing terribly tricky.

Also, if lots of images are being uploaded, it is no doubt a useful optimization to batch the copy commands, particular the image transitions.

Obviously, staging with an atlas is more involved, as stated above.

### Encoding an image element

The main trick of encoding an image element is figuring out how to reference the VkImage. For now, I'm not worrying about how to make those references stable across render calls, but can basically make the assumption that the scene is being encoded anew each time. In that case, I think the best approach is to count from 0, and add the image to a list of images kept in the render context. Then when it comes time to dispach the compute kernel for the fine rasterizer, build the array of images for the descriptor set from that list.

An optimization would be to recognize when the array is the same as the previous frame (likely common in UI contexts), and retain the previous descriptor set in that case.

The atlasing case is not hugely different, except for adding a uv subregion.

## Middle pipeline

The middle part of the pipeline is unaffected, as for those purposes the image is an opaque object. In particular, none of the middle stages need access to image data, just the geometry (which should be present in the encoded element).

## Fine rasterization

The fine rasterizer is where the image data is accessed. This should actually be pretty easy, it's little more than a [texture](https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/texture.xhtml) call in the shader.

The atlasing case would definitely be more complex, as the uv coordinates would have to be compared against the.

## Quality

Bilinear filtering is good enough for now, but a point for the future is that better quality is definitely possible, and desirable. Skia does [bicubic](https://bugs.chromium.org/p/skia/issues/detail?id=1253), and I think it's worth chasing that. But almost all of the work for that is in the shader; all the setup and resource management should stay the same.

**Comment by eliasnaur** [comment]
As mentioned in the [FillImage change](https://github.com/linebender/piet-gpu/commit/9417bdcf3fc30483f689db986b1888b1812f6024), I now believe images should be rendered outside piet-gpu, so they can be copied pixel-by-pixel in kernel4. In other words, I consider this issue fixed, but I'll leave it open for you to decide.

**Comment by DJMcNab** [comment]
We now have gradients working, and bitmap is tracked in #176. Closing [as discussed on zulup](https://xi.zulipchat.com/#narrow/stream/197075-gpu/topic/Old.20issues)
