### ISSUE TITLE
[MSAA] Artifacts in cardioid with 8xMSAA and 16xMSAA

### ISSUE THREAD

**Issue by armansito** [linebender/vello#380]
The msaa8 and msaa16 AA config's introduced in #377 render with artifacts:

![](https://user-images.githubusercontent.com/6933700/274439135-b6b1ff17-bf78-407c-885b-dde740a3a28d.png)

From @raphlinus: "I think the artifacts you're seeing are because of only 4 bits for winding number accumulation, and that test case is a good one for slamming lots of winding number increments into a small area. I'm not 100% sure though. An obvious way to validate that would be to try an 8 bit accumulator."

**Comment by raphlinus** [comment]
The [swar8](https://github.com/linebender/vello/tree/swar8) branch has 8 bit per sample winding number accumulation in msaa8 mode, and resolves these artifacts, confirming that it was an overflow.

There is a performance degradation (not carefully measured, but enough to be significant). The plan is to detect the number of path segments in the slice: if <= 7, then use 4 bit accumulation because overflow can't happen, otherwise 8.
