### ISSUE TITLE
Update raw-window-handle dependency

### ISSUE THREAD

**Issue by undersquire** [linebender/vello#411]
[Current version is 0.6](https://crates.io/crates/raw-window-handle/versions), while Vello is currently using 0.5 which causes issues when trying to use winit 0.29+.

**Comment by xStrom** [comment]
For an immediate solution, in order to use `winit` 0.29+ you want to use the `rwh_05` feature of `winit`, which enables `raw-window-handle` 0.5.

Right now `wgpu` has no published release with `raw-window-handle` 0.6, although the support is present in `trunk` thanks to [wgpu#4202](https://github.com/gfx-rs/wgpu/pull/4202). Once `wgpu` gets a new release that contains these changes we will update Vello accordingly.
