### ISSUE TITLE
`vello` should import `vello_shaders`

### ISSUE THREAD

**Issue by PoignardAzur** [linebender/vello#467]
The same preprocessor code is written twice:

- In `crates/shaders/src/compile/preprocess.rs`
- In `src/shaders/preprocess.rs`

[According to Raph](https://xi.zulipchat.com/#narrow/stream/197075-gpu/topic/The.20preprocess.20code.20seems.20to.20be.20duplicated), this is because the vello_shaders crate was meant for Skia integration, and currently isn't used by Vello.

We should fix that and remove the duplication.

**Comment by armansito** [comment]
We always intended for the main Vello crate to use `vello_shaders` but never got around to it. The crate supports generating native shaders (such as MSL) from the WGSL which allows external engines to target Metal, Vulkan, etc directly. This code path isn't exercised in the Vello repository but we have wanted to have native runners (i.e. alternative engines alongside wgpu) eventually but decided to put that in the backburner due to other priorities.

I think this issue can be repurposed as "Move to shader management via crates/shaders".
