### ISSUE TITLE
Version on `main` lags behind published crate

### ISSUE THREAD

**Issue by marcpabst** [linebender/vello#684]
Is this intentional? It's only a minor inconvenience but it leads to subtle incompatibilities (for example, `velato` will try to pull `0.2.1` from `crates.io` and I have trouble getting cargo to use the latests `main` form git instead)

**Comment by DJMcNab** [comment]
The history in 0.2.1 diverges from main, so it wouldn't really be accurate to use that version number on `main`, since the commit which was released was never actually present on main.

You are running into https://github.com/rust-lang/cargo/issues/5640. The workaround I'd suggest for your case is use a patched version of `velato` pointing at the patch you wish to use, or make a patch of Vello on main which has the version 0.2.0.

We're hoping to make a 0.3.0 release within the next month, which should resolve this. Although I recognise that a month is a long time.

That being said, we are considering following the pattern which Bevy uses, of "eagerly" bumping the version number to something incompatible, to avoid the expectation that this kind of transitive patching is directly supported. This is discussed in https://github.com/bevyengine/bevy/issues/6451. See also https://github.com/linebender/bevy_vello/issues/81

**Comment by marcpabst** [comment]
Thanks, I managed to solve my problem for now using a patched version!
